# Replace the "â¯" symbol in the prompt with "â†’"
[character]      # The name of the module we are configuring is "character"
symbol = "â†’"     # The "symbol" segment is being set to "â†’"
error_symbol = "âœ—"
use_symbol_for_status = true

[aws]
symbol = "îŒ½ "
disabled = false

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[directory]
truncation_length = 1
use_logical_path = true
truncate_to_repo = false

[git_branch]
symbol = "ï˜ "
truncation_symbol = ""

[git_status]
conflicted = " ğŸ³"
conflicted_count.enabled = true
ahead = "â†‘"
behind = "â†“"
untracked = "?"
untracked_count.enabled = true
stashed = "ğŸ“¦"
stashed_count.enabled = true
modified = "ğŸ“"
modified_count.enabled = true
staged = "S"
staged_count.enabled = true
renamed = ">>"
renamed_count.enabled = true
deleted = "âœ—"
deleted_count.enabled = true
show_sync_count = true
#prefix = ""
#suffix = " "
style = "dimmed red"

[hostname]
style = "blue"
ssh_only = false
disabled = false

[kubernetes]
symbol = "â›µ "
style = "purple"
disabled = false

[terraform]
disabled = false

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "
