# Replace the "â¯" symbol in the prompt with "â†’"
[character]      # The name of the module we are configuring is "character"
success_symbol = "â†’"     # The "symbol" segment is being set to "â†’"
error_symbol = "âœ—"

[aws]
symbol = "îŒ½ "
disabled = false

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[directory]
truncation_length = 1
use_logical_path = true
truncate_to_repo = false

[git_branch]
symbol = "ï˜ "
truncation_symbol = ""

[git_status]
conflicted = "ğŸ³${count}"
ahead = "â†‘"
behind = "â†“"
untracked = "?${count}"
stashed = "ğŸ“¦${count}"
modified = "ğŸ“${count}"
staged = "S${count}"
renamed = ">>${count}"
deleted = "âœ—${count}"
#prefix = ""
#suffix = " "
style = "dimmed red"

[hostname]
style = "blue"
ssh_only = false
disabled = false

[kubernetes]
symbol = "â›µ "
style = "purple"
disabled = false

[terraform]
disabled = false

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "
