[[snippets]]
  description = "direnv allow"
  command = "direnv allow ."
  output = ""

[[snippets]]
  description = "create k3s"
  command = "k3d cluster create k3d --kubeconfig-switch-context=false --kubeconfig-update-default=false --agents 2"
  output = ""

[[snippets]]
  description = "k8s get pods"
  command = "kubectl get po"
  output = ""

[[snippets]]
  description = "get cluster info"
  command = "kubectl cluster-info"
  output = ""

[[snippets]]
  description = "amend commit"
  command = "git commit --amend --no-edit"
  output = ""

[[snippets]]
  description = "pod version"
  command = "kubectl get pods -A  -o jsonpath=\"{..image}\" | xargs -n1  | sort -ub | rg src"
  output = ""

[[snippets]]
  description = "order pod by time"
  command = "kubectl get pods --sort-by=.metadata.creationTimestamp"
  output = ""

[[snippets]]
  description = "start colima"
  command = "colima start --network-address --cpu 4 --memory 8 #--vm-type qemu"
  output = ""

[[snippets]]
  description = "stop docker containers"
  command = "docker stop $(docker ps -q)"
  output = ""
